<?php

namespace Database\Seeders;

use App\Models\Post;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $description = "<h4 class='header-art'>Item description:</h4>
        <p>Get yourself this gicle&eacute; print of my artwork inspired by brazilian music, first edition used to illsutrate Snazzback music remix Soggy Pants. It shows a surrealist city full of characters, buildings and plants from another world. It is colourful, it is busy and well balanced.</p>
        <p>Printed in 8 ink profesional printer in 310 gsm fine art double matt paper. If you prefere it in cotton textured paper just drop me a Dm after the purchase.</p>
        <p>All prints have a 3cm white margin with handwritten signature, title and number edition.</p>
        <p>Limited editions of 50 on each size, available also as 16x16' by request</p>
        <p>The image will be hand signed before shipping including date and number of the edition.</p>
        <p>Colour tone may vary slightly in print.</p>
        <p>It is very important to me that this print gets to its final destination in perfect condition. That&rsquo;s why I always ship my products in a protective sleeve with cardboard backing, in a hard cardboard envelope for A4 and A3 sizes, and in a cardboard sturdy roll for A2 prints.</p>
        <p>Items cannot be exchanged or refunded once they have been dispatched.</p>
        <p>&nbsp;</p>
        <h3 class='header-art'>Materials used:</h3>
        <p>Made on photoshop, printed on 280 gsm acid free paper with 8 inks - gicl&eacute;e limited edition print</p>";
        
        $posts = array(

            // Babies & Kids
            [
                'id' => 1,
                'user_id' => mt_rand(2,6),
                'category_id' => 1,
                'title' => "Pampers Diaper",
                'slug' => Str::slug('Pampers Diaper'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 2,
                'user_id' => mt_rand(2,6),
                'category_id' => 1,
                'title' => "Baby Stroller Gray",
                'slug' => Str::slug('Baby Stroller Gray'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 3,
                'user_id' => mt_rand(2,6),
                'category_id' => 1,
                'title' => "Baby Stroller Pink",
                'slug' => Str::slug('Baby Stroller Pink'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            // Books
            [
                'id' => 4,
                'user_id' => mt_rand(2,6),
                'category_id' => 2,
                'title' => "Noli Me Tangere By Dr. Jose Rizal",
                'slug' => Str::slug('Noli Me Tangere By Dr. Jose Rizal'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 5,
                'user_id' => mt_rand(2,6),
                'category_id' => 2,
                'title' => "El Filibusterismo By Dr. Jose Rizal",
                'slug' => Str::slug('El Filibusterismo By Dr. Jose Rizal'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 6,
                'user_id' => mt_rand(2,6),
                'category_id' => 2,
                'title' => "Jose Rizal: Life, Works and Writings",
                'slug' => Str::slug('Jose Rizal: Life, Works and Writings'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 7,
                'user_id' => mt_rand(2,6),
                'category_id' => 2,
                'title' => "The Encyclopedia of Cooking Skills & Techniques",
                'slug' => Str::slug('The Encyclopedia of Cooking Skills & Techniques'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
           
            // Groceries
            [
                'id' => 8,
                'user_id' => mt_rand(2,6),
                'category_id' => 3,
                'title' => "7-Tonner Rice 1kg",
                'slug' => Str::slug('7-Tonner Rice 1kg'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 9,
                'user_id' => mt_rand(2,6),
                'category_id' => 3,
                'title' => "Quaker Oats 400G",
                'slug' => Str::slug('Quaker Oats 400G'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 10,
                'user_id' => mt_rand(2,6),
                'category_id' => 3,
                'title' => "Farmer's Choice Brown Rice",
                'slug' => Str::slug("Farmer's Choice Brown Rice"),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 11,
                'user_id' => mt_rand(2,6),
                'category_id' => 3,
                'title' => "Dried Mangoes 100g",
                'slug' => Str::slug('Dried Mangoes 100g'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 12,
                'user_id' => mt_rand(2,6),
                'category_id' => 3,
                'title' => "Banana Chips 100g",
                'slug' => Str::slug('Banana Chips 100g'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],

            // Health & Personal Care
            [
                'id' => 13,
                'user_id' => mt_rand(2,6),
                'category_id' => 4,
                'title' => "50pcs White Face Mask",
                'slug' => Str::slug('50pcs White Face Mask'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 14,
                'user_id' => mt_rand(2,6),
                'category_id' => 4,
                'title' => "50pcs Black Face Mask",
                'slug' => Str::slug('50pcs Black Face Mask'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 15,
                'user_id' => mt_rand(2,6),
                'category_id' => 4,
                'title' => "Faceshield",
                'slug' => Str::slug('Faceshield'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
           
            // Home Appliances
            [
                'id' => 16,
                'user_id' => mt_rand(2,6),
                'category_id' => 5,
                'title' => "HQ Blender",
                'slug' => Str::slug('HQ Blender'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 17,
                'user_id' => mt_rand(2,6),
                'category_id' => 5,
                'title' => "Premium Rice Cooker",
                'slug' => Str::slug('Premium Rice Cooker'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 18,
                'user_id' => mt_rand(2,6),
                'category_id' => 5,
                'title' => "Hanabishi Electric Fan",
                'slug' => Str::slug('Hanabishi Electric Fan'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 19,
                'user_id' => mt_rand(2,6),
                'category_id' => 5,
                'title' => "Hanabishi Dual Electric Burner",
                'slug' => Str::slug('Hanabishi Dual Electric Burner'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 20,
                'user_id' => mt_rand(2,6),
                'category_id' => 5,
                'title' => "Hanabishi Single Electric Burner",
                'slug' => Str::slug('Hanabishi Single Electric Burner'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],

            // Home & Living

            [
                'id' => 21,
                'user_id' => mt_rand(2,6),
                'category_id' => 6,
                'title' => "Blackout Curtain'",
                'slug' => Str::slug('Blackout Curtain'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],

            // Laptop & Computers
            [
                'id' => 22,
                'user_id' => mt_rand(2,6),
                'category_id' => 7,
                'title' => "ASUS 144HZ Gaming Monitor",
                'slug' => Str::slug('ASUS 144HZ Gaming Monitor'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],

            // Mobiles & Gadgets
            [
                'id' => 23,
                'user_id' => mt_rand(2,6),
                'category_id' => 8,
                'title' => "Lenovo Tablet",
                'slug' => Str::slug('Lenovo Tablet'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 24,
                'user_id' => mt_rand(2,6),
                'category_id' => 8,
                'title' => "Samsung Galaxy Tablet Tablet",
                'slug' => Str::slug('Samsung Galaxy Tablet Tablet'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],

            // Pet Care
            [
                'id' => 25,
                'user_id' => mt_rand(2,6),
                'category_id' => 9,
                'title' => "Meow Mix: Cat Food 90g",
                'slug' => Str::slug('Meow Mix: Cat Food 90g'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 26,
                'user_id' => mt_rand(2,6),
                'category_id' => 9,
                'title' => "Pedigree: Dog Food 90g",
                'slug' => Str::slug('Pedigree: Dog Food 90g'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 27,
                'user_id' => mt_rand(2,6),
                'category_id' => 9,
                'title' => "Dog Nozzle (Black)",
                'slug' => Str::slug('Dog Nozzle (Black)'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 28,
                'user_id' => mt_rand(2,6),
                'category_id' => 9,
                'title' => "Dog Nozzle (RED)",
                'slug' => Str::slug('Dog Nozzle (Black)'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
      
            [
                'id' => 29,
                'user_id' => mt_rand(2,6),
                'category_id' => 9,
                'title' => "Cat Harness",
                'slug' => Str::slug('Cat Harness'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],

            // School Materials
            [
                'id' => 30,
                'user_id' => mt_rand(2,6),
                'category_id' => 10,
                'title' => "Bond Paper",
                'slug' => Str::slug('Bond Paper'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 31,
                'user_id' => mt_rand(2,6),
                'category_id' => 10,
                'title' => "Yellow Paper",
                'slug' => Str::slug('Yellow Paper'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 32,
                'user_id' => mt_rand(2,6),
                'category_id' => 10,
                'title' => "Joy Color Pencils",
                'slug' => Str::slug('Joy Color Pencils'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 33,
                'user_id' => mt_rand(2,6),
                'category_id' => 10,
                'title' => "Mongol Pencils",
                'slug' => Str::slug('Mongol Pencils'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 34,
                'user_id' => mt_rand(2,6),
                'category_id' => 10,
                'title' => "Pencil Sharpener",
                'slug' => Str::slug('Pencil Sharpener'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 35,
                'user_id' => mt_rand(2,6),
                'category_id' => 10,
                'title' => "Spiderman Kid School Bag",
                'slug' => Str::slug('Spiderman Kid School Bag'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 36,
                'user_id' => mt_rand(2,6),
                'category_id' => 10,
                'title' => "BunnyHunny Kid School Bag",
                'slug' => Str::slug('BunnyHunny Kid School Bag'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 37,
                'user_id' => mt_rand(2,6),
                'category_id' => 10,
                'title' => "JoyBoy Art Coloring Book",
                'slug' => Str::slug('JoyBoy Art Coloring Book'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],

            // Toollits
            [
                'id' => 38,
                'user_id' => mt_rand(2,6),
                'category_id' => 11,
                'title' => "Ingco Tool Kit Handy man Tools",
                'slug' => Str::slug('Ingco Tool Kit Handy man Tools'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 39,
                'user_id' => mt_rand(2,6),
                'category_id' => 11,
                'title' => "Man Handy Tool Kits",
                'slug' => Str::slug('Man Handy Tool Kits'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 40,
                'user_id' => mt_rand(2,6),
                'category_id' => 11,
                'title' => "Ingco Hand Tools",
                'slug' => Str::slug('Ingco Hand Tools'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 41,
                'user_id' => mt_rand(2,6),
                'category_id' => 11,
                'title' => "Ingco Basic Tool Kits",
                'slug' => Str::slug('Ingco Basic Tool Kits'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 42,
                'user_id' => mt_rand(2,6),
                'category_id' => 11,
                'title' => "Makita Electric Driller",
                'slug' => Str::slug('Makita Electric Driller'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 43,
                'user_id' => mt_rand(2,6),
                'category_id' => 11,
                'title' => "Milwaukee Electric Heat Gun",
                'slug' => Str::slug('Milwaukee Electric Heat Gun'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 44,
                'user_id' => mt_rand(2,6),
                'category_id' => 11,
                'title' => "Tolsen Measuring Tape",
                'slug' => Str::slug('Tolsen Measuring Tape'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 45,
                'user_id' => mt_rand(2,6),
                'category_id' => 11,
                'title' => "GWS 060 Angle Grinder",
                'slug' => Str::slug('GWS 060 Angle Grinder'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 46,
                'user_id' => mt_rand(2,6),
                'category_id' => 11,
                'title' => "Angle Grinder 7.5-Amp 4-12/inch Grinding Wheels",
                'slug' => Str::slug('Angle Grinder 7.5-Amp 4-12/inch Grinding Wheels'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 47,
                'user_id' => mt_rand(2,6),
                'category_id' => 11,
                'title' => "Cushion Grip Phillips Screw Driver",
                'slug' => Str::slug('Cushion Grip Phillips Screw Driver'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],
            [
                'id' => 48,
                'user_id' => mt_rand(2,6),
                'category_id' => 11,
                'title' => "Flat-noe Pliers",
                'slug' => Str::slug('Flat-noe Pliers'),
                'description' => $description,
                'condition' => 'brand new',
                'value' => mt_rand(123,999),
                'shipping_options' => 'meetup and nationwide shipping',
                'tags' => 'tag1,tag2,tag3',
                'status' => Post::APPROVED,
                'created_at' => now()->subDay(),
            ],

        );



        Post::insert($posts);

        Post::all()->each(fn($post) => $post->addMedia(public_path("/img/tmp_files/posts/$post->id.png"))->preservingOriginal()->toMediaCollection('post_images'));
        
    }
}