{{-- blade-formatter-disable --}}
@component('mail::message')
Dear {{ $user->full_name }}, <br> <br>
Your account is now activated. You can now use your <span style="font-weight: bold; color: #2F89FC"> Albarter </span> account to access our platform.
@component('mail::panel')
Account Credential <br>
Email: {{ $user->email }} <br>
Password: {{ $password }} <br>
@endcomponent
<small>Note - This is a system autogenerated password. For security purposes please update your password as soon as you login to the application.</small>
<br><br>
Thanks,<br>
{{ config('app.name') }}
@endcomponent
